# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-05 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191001_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'товар в заказе', 'verbose_name_plural': 'товары в заказе'},
        ),
    ]
