# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-01 09:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_contact', models.CharField(max_length=200, verbose_name='контакт')),
                ('body_contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='текст')),
                ('adress_one_contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='первый адрес')),
                ('adress_toe_contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='второй адрес')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакт',
            },
        ),
        migrations.CreateModel(
            name='Dom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dom_title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('big_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='главный большой текст')),
            ],
            options={
                'verbose_name': 'дом',
                'verbose_name_plural': 'дом',
            },
        ),
        migrations.CreateModel(
            name='Dost_Oplat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_dostiop', models.CharField(max_length=200, verbose_name='доставка_и_оплата')),
                ('body_dostiop', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='текст')),
            ],
            options={
                'verbose_name': 'доставка_и_оплата',
                'verbose_name_plural': 'доставка_и_оплата',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_gallery', models.ImageField(blank=True, upload_to='gallery', verbose_name='vse_gallery')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотогаллерея',
                'ordering': ('title_gallery',),
            },
        ),
        migrations.CreateModel(
            name='Garantija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_garantija', models.CharField(max_length=200, verbose_name='гарантия')),
                ('body_garantija', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='гарантия')),
                ('body2_garantija', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='гарантия')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'гарантия',
                'verbose_name_plural': 'гарантия',
            },
        ),
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_katalog', models.CharField(max_length=200, verbose_name='каталог')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
            options={
                'verbose_name': 'каталог',
                'verbose_name_plural': 'каталог',
            },
        ),
        migrations.CreateModel(
            name='PodKatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_podkatalog', models.CharField(max_length=200, verbose_name='подкаталог')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('image_podkatalog', models.ImageField(blank=True, upload_to='podkatalog')),
            ],
            options={
                'verbose_name': 'подкаталог',
                'verbose_name_plural': 'подкаталог',
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slugt', models.SlugField(blank=True, verbose_name='slugt')),
                ('title_tovar', models.CharField(max_length=400, verbose_name='Товар')),
                ('image_start', models.ImageField(blank=True, upload_to='tovar')),
                ('body_tovar', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='текст')),
                ('cena2', models.CharField(blank=True, max_length=200, verbose_name='цена')),
                ('iden', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='артикль')),
                ('body2_tovar', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='текст2')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товар',
            },
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_usluga', models.CharField(max_length=200, verbose_name='услуга')),
                ('title2_usluga', models.CharField(blank=True, max_length=200, verbose_name='услуга')),
                ('body_usluga', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='услуга')),
                ('body2_usluga', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуга',
            },
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('body_zakaz', models.CharField(max_length=400, verbose_name='текст')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('comment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='podkatalog',
            name='tovar_podkatalog',
            field=models.ManyToManyField(to='polls.Tovar', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='katalog',
            name='podkatalog_katalog',
            field=models.ManyToManyField(blank=True, to='polls.PodKatalog', verbose_name='подкаталог'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_gallery',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Tovar'),
        ),
    ]
