# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-01 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='cena2',
        ),
        migrations.AddField(
            model_name='tovar',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, default=12, max_digits=10, verbose_name='цена2'),
            preserve_default=False,
        ),
    ]
