# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-05 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190404_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gallery2', models.CharField(blank=True, max_length=150)),
                ('photo_gallery2', models.ImageField(blank=True, upload_to='gallery2', verbose_name='vse_gallery2')),
            ],
            options={
                'verbose_name': 'Фото2',
                'verbose_name_plural': 'Фотогаллерея2',
                'ordering': ('title_gallery2',),
            },
        ),
        migrations.CreateModel(
            name='Gallery3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gallery3', models.CharField(blank=True, max_length=150)),
                ('photo_gallery3', models.ImageField(blank=True, upload_to='gallery3', verbose_name='vse_gallery3')),
            ],
            options={
                'verbose_name': 'Фото3',
                'verbose_name_plural': 'Фотогаллерея3',
                'ordering': ('title_gallery3',),
            },
        ),
        migrations.AddField(
            model_name='tovar',
            name='photo_tovar2',
            field=models.ManyToManyField(blank=True, to='polls.Gallery2', verbose_name='фото товара2'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='photo_tovar3',
            field=models.ManyToManyField(blank=True, to='polls.Gallery3', verbose_name='фото товара3'),
        ),
    ]
