# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190405_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluga',
            name='image_usluga',
            field=models.ManyToManyField(blank=True, to='polls.Gallery', verbose_name='фото услуги'),
        ),
    ]
