# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-10 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190409_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalog',
            name='image_catalog',
        ),
    ]
