# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-12 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_tovar_image_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='logo',
            field=models.ImageField(blank=True, upload_to='podkatalog'),
        ),
    ]
