# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_remove_katalog_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='slugt',
            field=models.SlugField(default=1, verbose_name='slugt'),
            preserve_default=False,
        ),
    ]
