# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-07 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_tovar_slugt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='iden',
            field=models.DecimalField(blank=True, decimal_places=2, default=12, max_digits=10, verbose_name='id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tovar',
            name='slugt',
            field=models.SlugField(blank=True, verbose_name='slugt'),
        ),
    ]
