# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20190507_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='cena',
            field=models.CharField(blank=True, max_length=20, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='iden',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='артикл'),
        ),
    ]
