# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190507_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='cena',
        ),
        migrations.AddField(
            model_name='tovar',
            name='cena2',
            field=models.CharField(blank=True, max_length=200, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='iden',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='артикль'),
        ),
    ]
