# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-30 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20190514_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantija',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
