# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-03 08:42
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_dom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='big_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=200, verbose_name='главный большой текст'),
        ),
    ]
