# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-05 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191001_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Фотогаллерея', 'verbose_name_plural': 'Фотогаллерея'},
        ),
        migrations.AlterModelOptions(
            name='tovar',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='zakaz',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='tovar',
            name='photo_tovar',
            field=models.ManyToManyField(blank=True, to='polls.Gallery', verbose_name='фото товара'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo_gallery',
            field=models.ImageField(blank=True, upload_to='gallery', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_gallery',
            field=models.CharField(max_length=400, verbose_name='название фото'),
        ),
    ]
