# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-05 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191005_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluga',
            name='image_usluga',
            field=models.ManyToManyField(blank=True, to='polls.Gallery', verbose_name='фото услуги'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='image_start',
            field=models.ImageField(blank=True, upload_to='tovar', verbose_name='основное фото товара'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='в наличии'),
        ),
    ]
