# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-03 15:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190403_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_usluga', models.CharField(max_length=200, verbose_name='услуга')),
                ('body_usluga', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='услуга')),
                ('body2_usluga', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуга',
            },
        ),
        migrations.AlterField(
            model_name='dom',
            name='big_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='главный большой текст'),
        ),
    ]
