# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-04 08:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_garantija'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254)),
                ('body_zakaz', models.CharField(max_length=400, verbose_name='текст')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('comment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
    ]
