# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_usluga_image_usluga'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluga',
            name='title2_usluga',
            field=models.CharField(blank=True, max_length=200, verbose_name='услуга'),
        ),
    ]
