# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-10 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_katalog_image_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='image_start',
            field=models.ImageField(blank=True, upload_to='tovar'),
        ),
    ]
