# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-12 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_katalog_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalog',
            name='logo',
        ),
    ]
