# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0021_auto_20190930_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(blank=True, max_length=150)),
                ('order_email', models.EmailField(blank=True, max_length=254)),
                ('order_phone', models.CharField(blank=True, max_length=150)),
                ('order_create', models.DateTimeField(auto_now_add=True)),
                ('order_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('product_create', models.DateTimeField(auto_now_add=True)),
                ('product_update', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('tovar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Tovar')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('status_create', models.DateTimeField(auto_now_add=True)),
                ('status_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'статусы заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Status'),
        ),
    ]
