# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-01 10:26
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commnt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_adress',
            field=models.CharField(blank=True, max_length=300, verbose_name='адрес доставки'),
        ),
    ]
