# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-01 10:52
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191001_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amound',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='commnt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_adress',
            field=models.CharField(blank=True, default=None, max_length=300, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_phone',
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='orice_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='tovar',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Tovar'),
        ),
    ]
